module Config
  CONSUMER_KEY = 'YOUR_CONSUMER_KEY'.freeze
  CONSUMER_SECRET = 'YOUR_CONSUMER_SECRET'.freeze
  ACCESS_TOKEN = 'YOUR_ACCESS_TOKEN'.freeze
  ACCESS_TOKEN_SECRET = 'YOUR_ACCESS_TOKEN_SECRET'.freeze
end